services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm
      - TZ=Europe/Moscow
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm
      - TZ=Europe/Moscow
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
